version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.2
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.3.0
    - 6.3.1
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.7
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.4
    - 13.1.5
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: "@nivo/pie"
    versions:
    - 0.63.1
    - 0.67.0
  - dependency-name: "@nivo/bar"
    versions:
    - 0.64.0
    - 0.67.0
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: react-icons
    versions:
    - 4.1.0
